version: '3.2'

services:
    redis-commander:
      container_name: redis-commander
      hostname: redis-commander
      image: rediscommander/redis-commander:latest
      restart: always
      environment:
        - REDIS_HOSTS=redis:6379
      ports:
        - "8082:8081"
        
    postgres:
        volumes:
            - "pg_data:/var/lib/postgresql/data"
        image: postgres
        restart: always 
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=12345678

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            - 'PGADMIN_DEFAULT_EMAIL=thigas@teste.com.br' 
            - 'PGADMIN_DEFAULT_PASSWORD=12345678' 
        ports:
            - 8080:80

    redis:
        image: redis
        ports:
            - 6379:6379

volumes:
  pg_data: